### ISSUE TITLE
convert.im6: no images defined `/home/name/Pictures/ssample/_site/history/mm-imagesequence/640.jpg' @ error/convert.c/ConvertImageCommand/3044.

### ISSUE THREAD

**Issue by santoshgistto** [Jack000/Expose#12]

**Comment by Jack000** [comment]
unfortunately "no images defined" could be a number of different issues. What system are you on? Are there any errors or warnings prior to this message?

do you get any errors if you run the convert command by itself?

    convert ./mm-imagesequence/blah.jpg -resize "640"x"640" -quality "92" +profile '*' test.jpg

**Comment by defermat** [comment]
not sure if this is the same problem that @santoshgistto is having, but I'm seeing the following issue when trying to use an `imagesequence` folder.

I'm running on OS X 10.10.5 Yosemite with the following installed by brew:

```
$ brew install jpeg
Warning: jpeg-8d already installed
$ brew install imagemagick
Warning: imagemagick-6.8.9-8 already installed
$ brew install ffmpeg
Warning: ffmpeg-2.5.2 already installed
```

```
$ convert -list configure
DELEGATES      bzlib mpeg freetype jng jpeg lzma png xml zlib
```

And I get the following warnings/errors when running expose with a folder of `jpg`s that has `imagesequence` in the folder name:

```
$ expose
Scanning directories..
Populating nav.
Reading files.convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/501.
convert: no images defined `txt:-' @ error/convert.c/ConvertImageCommand/3187.
identify: no decode delegate for this image format `' @ error/constitute.c/ReadImage/501.
identify: no decode delegate for this image format `' @ error/constitute.c/ReadImage/501.
/Users/u/github/Expose/expose.sh: line 403: [: : integer expression expected
/Users/u/github/Expose/expose.sh: line 403: [: : integer expression expected
/Users/u/github/Expose/expose.sh: line 403: [: : integer expression expected
/Users/u/github/Expose/expose.sh: line 403: [: : integer expression expected
/Users/u/github/Expose/expose.sh: line 403: [: : integer expression expected
/Users/u/github/Expose/expose.sh: line 403: [: : integer expression expected
/Users/u/github/Expose/expose.sh: line 410: res*height/width: division by 0 (error token is "h")

Building HTML
Starting encode
```

**Comment by defermat** [comment]
nevermind, figured it out.  I had `.DS_Store` in the `imagesequence` directory.  after deleting, all was well.

**Comment by Jack000** [comment]
oh ok, script should probably handle that case though. I'll have a look at that too.

**Comment by santoshgistto** [comment]
@Jack000  i am using ubuntu

**Comment by santoshgistto** [comment]
here is detial logs:

convert.im6: unable to open image `/tmp/tmp.qbSpbwQICd/temp.jpg': No such file or directory @ error/blob.c/OpenBlob/2638.
convert.im6: no images defined `/home/santosh/Pictures/sssss/_site/bidar/mm-imagesequence/640.jpg' @ error/convert.c/ConvertImageCommand/3044.

**Comment by Jack000** [comment]
defermat: latest patch should fix problems related to non-image files in imagesequence directories

santoshgistto: this either means your temp directory was not writable or the video thumbnail step failed. Could you try checking the permissions of /tmp/tmp.qbSpbwQICd/ (or which ever new tmp directory the script creates)

if that was not the issue, then this command failed:

    ffmpeg -loglevel error -y -i "$filepath" -vf "select=gte(n\,1)" -vframes 1 -qscale:v 2 "$temppath"

did you get any ffmpeg errors? the full output would help here.

**Comment by MrBramme** [comment]
I seem to have a similar issue. Working on windows 7 using cygwin64 terminal (tried the git bash first but that doesn't support all the commands).

I moved the folder around a bit to make sure there's no issue with reading/writing rights. Tried running the terminal in admin mode as well.

My error:

```
convert.exe: unable to open image `/cygdrive/c/temp/temp/DSCN5470.JPG': No such file or directory @ error/blob.c/OpenBlob/2701.
convert.exe: no images defined `txt:-' @ error/convert.c/ConvertImageCommand/3230.
identify.exe: unable to open image `/cygdrive/c/temp/temp/DSCN5470.JPG': No such file or directory @ error/blob.c/OpenBlob/2701.
identify.exe: unable to open image `/cygdrive/c/temp/temp/DSCN5470.JPG': No such file or directory @ error/blob.c/OpenBlob/2701.
identify.exe: unable to open image `/cygdrive/c/temp/temp/DSCN5470.JPG': No such file or directory @ error/blob.c/OpenBlob/2701.
c:/temp/expose/expose.sh: line 422: [: : integer expression expected
c:/temp/expose/expose.sh: line 422: [: : integer expression expected
c:/temp/expose/expose.sh: line 422: [: : integer expression expected
c:/temp/expose/expose.sh: line 422: [: : integer expression expected
c:/temp/expose/expose.sh: line 422: [: : integer expression expected
c:/temp/expose/expose.sh: line 422: [: : integer expression expected
c:/temp/expose/expose.sh: line 429: res*height/width: division by 0 (error token is "width")
```

the image in question is the first one in line to be processed. seems to break on that and not move on. It does create the folders and index.html sites, but nothing else.

**Comment by defermat** [comment]
sweet, thanks @Jack000 !

**Comment by Jack000** [comment]
MrBramme:

I'm assuming here that C:/temp/temp is a folder you created and where the source image resides?

Can you verify that /cygdrive/c/temp/temp/DSCN5470.JPG is accessible (try to do a mv or something), as opposed to C:/temp/temp/DSCN5470.JPG , then try

    identify -format "%m" /cygdrive/c/temp/temp/DSCN5470.JPG
    identify -format "%m" C:/temp/temp/DSCN5470.JPG

Is your imagemagick installed through windows or cygwin? Is your script directory on a different drive than C:?

**Comment by MrBramme** [comment]
@Jack000 
Correct, c:/temp/temp is the folder contaning a set of 29 JPG images.

I used the mv command and succesfully moved an image to another folder. so there shouldn't be an issue with accessibility.

I did however forget to instakke Imagemagick for cygen (installed the windows version). I've just done that but still have an issue (see below). I'm assuming I did something wrong installing cygwin or Imagemagick. I did follow the "test" for correct install on the ImageMagick site like this:
```
convert logo: logo.gif
identify logo.gif
display logo.gif
```
While i didn't get any errors running this, I also didn't see anything happen. So I assume the install didn't work as planned.

As for the expose script response I got now:
```
$ expose
Scanning directories.
Populating nav.
Reading files.c:/temp/Expose/expose.sh: line 422: [: : integer expression expected
c:/temp/Expose/expose.sh: line 422: [: : integer expression expected
c:/temp/Expose/expose.sh: line 422: [: : integer expression expected
c:/temp/Expose/expose.sh: line 422: [: : integer expression expected
c:/temp/Expose/expose.sh: line 422: [: : integer expression expected
c:/temp/Expose/expose.sh: line 422: [: : integer expression expected
c:/temp/Expose/expose.sh: line 429: res*height/width: division by 0 (error token is "width")

Building HTML
Starting encode
c:/temp/Expose/expose.sh: line 944: rsync: command not found
```

**Comment by Jack000** [comment]
if you run

    which convert

that should tell you whether your imagemagick is cygwin or windows (cygwin path should be something like /usr/bin/convert).

Unfortunately windows programs have problems with cygwin paths. Are you getting imagemagick from the cygwin setup.exe? It's possible you might have to uninstall the windows version, but I find that unlikely.

also you'll need to install rsync (also from setup.exe) to transfer the template files at the end there.

**Comment by MrBramme** [comment]
Hi Jack000,

Seems I messed something up with my cygwin. I removed it and made a fresh install (including both rsync & imagemagick immediately). After that it worked just fine!

Thanks for the help!

**Comment by Jack000** [comment]
no problem! let me know if you have any other questions.
