### ISSUE TITLE
How do you find polygons

### ISSUE THREAD

**Issue by podviaznikov** [Jack000/Expose#13]
>Use a polygon to wrap text around shapes. The polygon is defined by 3 or more points in a JSON blob. Units are again in percentages.

Do you use some tool to make a polygon? Can you describe your flow in more details please?

**Comment by Jack000** [comment]
I open up photoshop, scale the image to 1000x1000 pixels (it'll be stretched), and use the ruler to check the cursor position. This way horizontal and vertical measurements are multiples of 10, so it's easy to see what percent the points are at.

Or you can just estimate and guess/check via the draft feature, which should be fine if you just want a slope or something.

**Comment by podviaznikov** [comment]
@Jack000 thanks!
