### ISSUE TITLE
Does not warn about missing ffmpeg

### ISSUE THREAD

**Issue by prayerslayer** [Jack000/Expose#14]
I ran it for the first time (OSX 10.10.2) and it complained about missing ImageMagick, so I installed it. Then it just ignored my videos. It was only after I installed ffmpeg that expose.sh processed my videos. It should check for `ffmpeg` when there are videos in the gallery.

Great work btw, thank you very much.

**Comment by Jack000** [comment]
added a warning in the latest commit https://github.com/Jack000/Expose/commit/97b8d4664a26c7e0bf1eba4fc5185af0144a745c
