### ISSUE TITLE
videos generated in draft mode, but otherwise I only get the poster image

### ISSUE THREAD

**Issue by mandeldl** [Jack000/Expose#15]
First off, great work!  
I'm not too familiar with shell scripts and I don't see any error logs, so I'll do my best to describe what's happening:

Running ```expose -d``` in the folder generates all the files, including video.
```
_site
|- img7851
|  |- 640.jpg
|  |- 1024-h264.mp4
|  |- 1024.jpg
```

But running plain ol' ```expose``` (after deleting the previously created ```_site``` folder) will only generate the poster-image for the video inside its folder, not the video file.

```
_site
|- img7851
|  |- 640.jpg
```

I'm running zsh in Mac OS 10.8.5.  It is an older machine, so perhaps it's a hardware issue?
Imagemagick and ffmpeg are installed:
```
identify -version                                 127 ↵
Version: ImageMagick 6.9.0-9 Q16 x86_64 2015-03-02 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: DPC Modules
Delegates (built-in): bzlib freetype jng jpeg ltdl lzma png xml zlib
```

```
ffmpeg
ffmpeg version 2.5.4 Copyright (c) 2000-2015 the FFmpeg developers
  built on Feb 15 2015 20:18:54 with Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/2.5.4 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-libx264 --enable-libmp3lame --enable-libvo-aacenc --enable-libxvid --enable-vda
```

**Comment by Jack000** [comment]
this likely means that single-pass CRF coding with ffmpeg (used in draft mode) works, but 2-pass VBR did not. Did you get any ffmpeg errors?

try running the first pass in ffmpeg:

    ffmpeg -loglevel info -y -i /your/video/file.mp4 -c:v libx264 -threads 0 -profile:v high -pix_fmt yuv420p -preset slow -b:v 5M -maxrate 10M -bufsize 10M -pass 1 -an -f mp4 /dev/null

this should generate several ffmpeg log files in your CWD.
I'm assuming you haven't changed the video presets, and it's trying to compile to h264 and vp8?

**Comment by mandeldl** [comment]
Thanks, you're correct this did generate some ffmpeg logs and I'll investigate.  No, I hadn't changed any settings in the script file.

**Comment by Jack000** [comment]
so those log files are normal, they're a part of the 2-pass encode process. If they're empty that could indicate problems.

**Comment by davidbgk** [comment]
After a few hours trying to figure out what is going on with that same issue, I realized that it's because my video is portrait oriented and as such is excluded from the whole encoding thing with that line: https://github.com/Jack000/Expose/blob/master/expose.sh#L829

There is no error whatsoever and it works in draft mode because the check is not performed in that case. Is there a reason to that?
