### ISSUE TITLE
Theme two, text placement

### ISSUE THREAD

**Issue by jwaynelee** [Jack000/Expose#21]
Theme 2 currently places any text before its associated image, except for the first (masthead) image. This means (I think) that there is no way to place any text at the very end of the page (in other words, no way to have the page end with text, instead of ending with an image.)

I created my own version of theme 2, and changed its post-template.html file to place the "post" div after the "image" div.

That solves the issue with not being able to put text at the very end of the page, but now there's no way to have the page *start* with text (except for the masthead text.)

Would it be useful to allow the name of the text file to include something that indicates whether the text goes before *or* after the associated image?

**Comment by Jack000** [comment]
so I think this should be a part of the theme rather than a specific flag in the script. I pushed a change to make this available by default. eg:

    ---
    class: textafter
    ---
    text stuff blah blah

**Comment by jwaynelee** [comment]
Thanks, that worked.
