### ISSUE TITLE
Can this be hosted with github pages?

### ISSUE THREAD

**Issue by meekrosoft** [Jack000/Expose#25]
Hi,
Thanks for the cool tool!
More of a question than an issue, but...can expose websites be hosted by github pages?
Best,
Mike

**Comment by d2s** [comment]
@meekrosoft Should be possible, as this is a static site generator.

**Comment by Jack000** [comment]
yep, but not in the same way as jekyll since jekyll is integrated into github.

You'd have to download/run expose and commit the _site folder
