### ISSUE TITLE
Gallery Headers

### ISSUE THREAD

**Issue by thebradbain** [Jack000/Expose#28]
Hi, I noticed on jack.ventures (awesome photography by the way) that your galleries each had headers / variable text sizes in slides. Is this at all possible in this tool you released, or are you keeping that a trade secret? 

Thanks!

**Comment by arktype** [comment]
I just downloaded the source to use as a starting point for a project, and it looks like variable text size and captions are part of it. The text size is set client side based on browser size.

**Comment by arktype** [comment]
It looks like markdown works within the text files for headings and such (but that won't allow for variable positioning like on jack.ventures, not sure of a good way to do that yet).

**Comment by Jack000** [comment]
I actually just insert a bit of html for positioning. Regular html is passed through.
