### ISSUE TITLE
Handle /bin/sed: Argument list too long 

### ISSUE THREAD

**Issue by jeffjose** [Jack000/Expose#3]
When working on a directory with huge number of images, Expose runs into `/bin/sed: Argument list too long` errors. This is probably a command line limitation, but Expose should handle it. Possibly chunk it the input files?

**Comment by Jack000** [comment]
I haven't actually been able to replicate this error, but I think I see what could be the problem. This commit should fix any sed input length related issues: https://github.com/Jack000/Expose/commit/91c8dc0f6ba5d2750a405d048dcb9a8077d6525f
