### ISSUE TITLE
Can it be integrated with JavaScript BPG decoder?

### ISSUE THREAD

**Issue by vi** [Jack000/Expose#5]
I look for static album generators that can do [BPG](http://bellard.org/bpg/).

As browsers don't usually support new picture formats, BPG offers a [JavaScript decoder](https://github.com/mirrorer/libbpg/blob/master/html/bpgdec8.js) that adds this feature without browser support.

But that turns usual `<img>`s to `<canvas>`, so it does not typically works with galleries.

**Comment by Jack000** [comment]
imagemagick does support BPG so it shouldn't be a problem. Canvas is not a big issue either, but to get it all working you'd need to make a custom theme that had the javascript decoder.

Given the niche nature of the format, maybe just fork the repo? I think this may not be in the scope of the main project.

**Comment by Danfrost1** [comment]
What does all this code mean?

**Comment by vi** [comment]
Which code? `bpgdec8.js`?
